Adds Not type class, Fixes #239
sebastiaanvisser/clay pull request #240
Opened 2022-06-08 21:29 UTC by Skyfold

The `not` pseudo selector can only be applied to one argument at a time in most browsers, Safari seems to be the exception. The instance for `Not Refinement` allows you to apply `Not` to multiple arguments, however, there is no contaminator to combine two `Refinement` directly.

2022-06-09 08:55 UTC, turion requested changes
Code is looking great :) can you add two simple unit tests using each instance?

2022-06-28 21:17 UTC, Skyfold commented
I've added four simple tests in PseudoSpec.hs

There is one disadvantage to the current type class approach: if you write `not ".test"` it is ambiguous if the `".test"` is a `Selector` or a `Refinement`.

2022-06-29 08:30 UTC, turion commented
Yes, that's a disadvantage. Recently, a similar issue was raised: https://github.com/sebastiaanvisser/clay/issues/241

2024-10-24 09:53 UTC, turion requested changes
I think this PR is still a useful addition!

2024-10-24 09:53 UTC, turion commented on src/Clay/Render.hs
> +
```suggestion
```

2024-10-24 09:55 UTC, merged

2024-10-31 16:42 UTC, chungyc commented
FYI, this can break existing code when the type for the selector is not explicit.  For example,

```haskell
img # (not ".keep-colors" <> "src" $= ".svg")
```

will now [result in an ambiguous type].

This is not a big deal for me (I plan to simply add an explicit type annotation), but it should at least be mentioned in any release notes.

[result in an ambiguous type]: https://github.com/chungyc/site-blog/actions/runs/11615631342/job/32346666801