Fix rendering of the Number type
sebastiaanvisser/clay pull request #256
Opened 2023-11-11 10:33 UTC by ddssff

Do not use the the Show instance of Clay.Property.Number for rendering.  Instead add an instance of Pretty that uses the showFixed function of the underlying Fixed value.  Adds a test case to spec/Clay/MediaSpec.hs that demonstrates the resulting output of the keyframes function.

2023-11-11 16:31 UTC, turion commented
Ah, I wasn't aware the rendering of `Number` is broken. Can you give an example of what went wrong?

2023-11-12 11:18 UTC, ddssff commented
Without fix:

`Number {unNumber = 0.00000}% {visibility:visible;}`

With fix:

`0% {visibility:visible;}`

2023-11-13 11:33 UTC, turion commented
I think even better would be to use `fromText $ cssNumberText p`. I definitely wouldn't want to incur an extra dependency for this.

2023-11-13 15:44 UTC, ddssff commented
Whatever works!

2023-11-13 19:31 UTC, ddssff commented
Ok, pretty dependency removed.

2023-11-14 08:35 UTC, turion requested changes
There are some warnings about redundant imports that should be fixed, otherwise looking great!

2023-11-14 10:24 UTC, ddssff reviewed
Looks good.

2023-11-14 10:26 UTC, ddssff reviewed
:+1:   Not sure how these reviews are supposed to work.

2023-11-14 10:50 UTC, turion commented on src/Clay/Render.hs
> +    [ fromText (cssNumberText p)
This makes the `pack` import obsolete, can you remove it?

2023-11-15 02:14 UTC, ddssff commented
Warnings fixed.

2023-11-15 08:29 UTC, merged

2023-11-15 08:29 UTC, turion commented
Thanks a lot!